const paintingData = [
  {
    id: 1,
    firstName: "Jean Honore",
    lastName: "Fragonard",
    sat: false,
    sun: true,
    favorite: true,
    title: "Woman reading",
  },
  {
    id: 2,
    firstName: "Ivan",
    lastName: "Kramskoi",
    sat: true,
    sun: true,
    favorite: false,
    title: "Portrait of an unknown woman",
  },
  {
    id: 3,
    firstName: "Amadeo",
    lastName: "Modigliani",
    sat: true,
    sun: false,
    favorite: false,
    title: " Jeanne Hébuterne",
  },
  {
    id: 4,
    firstName: "Amadeo",
    lastName: "Modigliani",
    sat: true,
    sun: false,
    favorite: false,
    title: "Maybe Dr.Deveraigne",
  },
  {
    id: 5,
    firstName: "Rembrandt",
    lastName: "van Rijn",
    sat: true,
    sun: true,
    favorite: false,
    title: "Self-portrait",
  },
  {
    id: 6,
    firstName: "Rembrandt",
    lastName: "van Rijn",
    sat: true,
    sun: true,
    favorite: false,
    title: "Old man",
  },
  {
    id: 7,
    firstName: "Ilya",
    lastName: "Repin",
    sat: true,
    sun: false,
    favorite: false,
    title: "Pisemsky",
  },
  {
    id: 8,
    firstName: "Martiros",
    lastName: "Saryan",
    sat: true,
    sun: true,
    favorite: false,
    title: "Portrait of a woman",
  },
  {
    id: 9,
    firstName: "Amadeo",
    lastName: "Modigliani",
    sat: true,
    sun: false,
    favorite: false,
    title: "Another Jeanne Hébuterne",
  },
  {
    id: 10,
    firstName: "Ilya",
    lastName: "Repin",
    sat: true,
    sun: false,
    favorite: false,
    title: "Musorgsky",
  },
];

export default paintingData;
